# Site
title: by and for engineers
email: yuliinfo@gmail.com
description: >
  技術や気になったものを思いつきと気まぐれで書いています
url: "https://yulii.github.io"
author: Ryo Yoneyama (@yulii)
copyright: "2008-2015, yulii"

# Config
timezone: "Asia/Tokyo"

# Common Variables
author_img_path: "/img/site/yulii.jpg"
cover_img_path: "/img/site/by-and-for-engineers.jpg"

# Build
exclude: ["bin", "vendor", "Gemfile", "Gemfile.lock"]
permalink: /:title-:year:month:day.html
markdown: kramdown
redcarpet:
  extensions: [
    "footnotes",
    "strikethrough",
    "tables"
  ]
compress_html:
  clippings: all
  comments:  ["<!-- ", " -->"]
  endings:   []

# Pagination
paginate: 5
paginate_path: /:num/

# Gem
gems:
  - jekyll-paginate
  - jemoji
