# Site
title: by and for engineers
email: yuliinfo@gmail.com
description: >
  技術や気になったものを思いつきと気まぐれで書いています
url: "https://yulii.github.io"

# Config
timezone: "Asia/Tokyo"

# Build
exclude: ["bin", "vendor", "Gemfile", "Gemfile.lock"]
permalink: /:title-:year:month:day.html
markdown: redcarpet
redcarpet:
  extensions: [
    "footnotes",
    "strikethrough",
    "tables"
  ]

# Pagination
paginate: 5
paginate_path: /:num

# Gem
gems:
  - jemoji
