# Site settings
title: by and for engineers
email: yuliinfo@gmail.com
description: >
  技術や気になったものを思いつきと気まぐれで書いています
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yulii.net"

# Build settings
permalink: /:title-:year:month:day.html
markdown: kramdown
exclude: ["bin", "vendor", "Gemfile", "Gemfile.lock"]

