tex:
  type: category
  face: TeX
  description: "TeX の書き方やスタイルファイルによる独自マクロ作成などTeX による文章作成のための記事です。"
pdf:
  type: tag
  face: PDF
php:
  type: category
  face: PHP
  description: "PHP プログラミングの技術メモやスニペットコードをまとめた記事です。"
