database:
  type: category
  face: "データベース"
  description: "リレーショナルデータベースやNoSQL などストレージに関するTips や設計思想メモ"
eclipse:
  type: tag
  face: Eclipse
  description: "統合開発環境 IDE のEclipse に関する設定やショートカットキーまとめ"
pdf:
  type: tag
  face: PDF
php:
  type: category
  face: PHP
  description: "PHP プログラミングの技術メモやスニペットコードをまとめた記事です。"
tex:
  type: category
  face: TeX
  description: "TeX の書き方やスタイルファイルによる独自マクロ作成などTeX による文章作成のための記事です。"
ubuntu:
  type: tag
  face: Ubuntu
  description: "Ubuntu の設定に関するメモやサーバー構築ノウハウ"
unix:
  type: category
  face: Unix / Linux
  description: "UNIXやLinuxでのサーバー設定やコマンドに関する各種メモ書き"
