apache:
  type: tag
  face: Apache
  description: "Webサーバソフトウェア Apacheのインストール方法から動作確認、メンテナンス、チューニング方法などの解説記事です。"
c-lang:
  type: category
  face: C言語
  description: "C言語プログラミングの技術メモやスニペットコードをまとめた記事です。"
centos:
  type: tag
  face: CentOS
  description: "CentOS に関する設定やサーバー構築メモ"
database:
  type: category
  face: "データベース"
  description: "リレーショナルデータベースやNoSQL などストレージに関するTips や設計思想メモ"
eclipse:
  type: tag
  face: Eclipse
  description: "統合開発環境 IDE のEclipse に関する設定やショートカットキーまとめ"
ffmpeg:
  type: tag
  face: FFmpeg
  description: "FFmpeg / FFserver による動画エンコードやライブストリーミング配信サーバーの構築メモ"
java:
  type: category
  face: Java
  description: "Java プログラミングのスニペットや環境構築のメモ"
javascript:
  type: category
  face: JavaScript
  description: "JavaScript プログラミングのスニペット、コーディングや高速化のTips まとめ。"
maven:
  type: tag
  face: Maven
  description: "プロジェクトのライフサイクル全体を管理できる Maven の利用方法ドキュメントです。Maven は Project Object Model (POM) に基づき、プロジェクトのビルド、テスト、ドキュメンテーション、成果物の配備が出来ます。"
memcached:
  type: tag
  face: memcached
  description: "分散メモリキャッシュシステム memcached の使い方や設定の技術記事です。memcached を利用した開発メモをまとめました。"
mysql:
  type: tag
  face: MySQL
  description: "MySQL の設定やSQL チューニング、インデックス設計など気になった事をまとめました。"
network:
  type: category
  face: ネットワーク
  description: "インターネットの基礎技術に関連した話題。ネットワーク周りの勉強資料まとめ。"
pdf:
  type: tag
  face: PDF
php:
  type: category
  face: PHP
  description: "PHP プログラミングの技術メモやスニペットコードをまとめた記事です。"
server:
  type: category
  face: サーバー
  description: "サーバー構築作業や設定方法の技術メモ"
subversion:
  type: tag
  face: Subversion
  description: "バージョン管理システム Subversion の使い方やサーバー設定についての技術ドキュメントです。"
tex:
  type: category
  face: TeX
  description: "TeX の書き方やスタイルファイルによる独自マクロ作成などTeX による文章作成のための記事です。"
tomcat:
  type: tag
  face: Tomcat
  description: "Java サーブレット、JSP を処理するアプリケーションサーバ Tomcat の使い方や設定方法の備忘録です。"
ubuntu:
  type: tag
  face: Ubuntu
  description: "Ubuntu の設定に関するメモやサーバー構築ノウハウ"
unix:
  type: category
  face: Unix / Linux
  description: "UNIXやLinuxでのサーバー設定やコマンドに関する各種メモ書き"
windows:
  type: category
  face: Windows
  description: "Windows の設定や環境構築についての記事です。バッチファイルの記述方法の技術ドキュメントをまとめました。"

