version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - restore_cache:
          key: yulii-github-io-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle --jobs=4
      - save_cache:
          key: yulii-github-io-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Build jekyll templates
          command: bundle exec jekyll build

  update:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Update dependencies
          command: bundle update
      - run:
          name: Send auto update pull request
          command: |
            test -z "$(git status -s Gemfile.lock 2> /dev/null)" && exit 0
            BRANCH="auto-bundle-update-${CIRCLE_BUILD_NUM}"
            git config --local user.email yone.info@gmail.com
            git config --local user.name 'yulii via ci'
            git add Gemfile.lock
            git commit -m 'Bundle update'
            git branch -M $BRANCH
            git push origin $BRANCH

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - update:
          requires:
            - build
          filters:
            branches:
              only: auto-bundle-update
