version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - type: cache-restore
        key: yulii-github-io-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle --jobs=4
      - type: cache-save
        key: yulii-github-io-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      - run: bundle exec jekyll build
